Version: 0.02
phases:
    install:
      commonds:
       - echo installing webserver
       - sudo apt update
       - sudo apt install apache2 -y
    build:
      commonds:
       - echo building file
       - cp index.html /var/www/html/
    post_build:
      commonds:
       - echo configured
artifacts:
    file:
      - "**/*"
    
   
